
#ifndef _UCSAPI_H_INCLUDED
#define _UCSAPI_H_INCLUDED

#include "UCSAPI_Basic.h"
#include "UCSAPI_Type.h"
#include "UCSAPI_Error.h"
#include "UCBioAPI_Export.h"

#ifdef __cplusplus
extern "C" {
#endif
	
#ifndef _UCSAPI_LOAD_LIBRARY

	UCSAPI_RETURN UCSAPI UCSAPI_ServerStart(
		IN UCSAPI_UINT32 MaxTerminal,
		IN UCSAPI_UINT32 Port,
		IN UCSAPI_UINT32 Reserved,
		IN UCSAPI_CALLBACK_EVENT_HANDLER CallbackEventFunction);

	UCSAPI_RETURN UCSAPI UCSAPI_ServerStop();

	UCSAPI_RETURN UCSAPI UCSAPI_AddUserToTerminal(
		IN UCSAPI_UINT16		ClientID,
		IN UCSAPI_UINT32		TerminalID,
		IN UCSAPI_BOOL			IsOverwrite,
		IN UCSAPI_USER_DATA_PTR pUserData);

	UCSAPI_RETURN UCSAPI UCSAPI_DeleteUserFromTerminal(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID, 
		IN UCSAPI_UINT32  UserID);

	UCSAPI_RETURN UCSAPI UCSAPI_DeleteAllUserFromTerminal(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID); 

	UCSAPI_RETURN UCSAPI UCSAPI_GetUserCountFromTerminal(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID);

	UCSAPI_RETURN UCSAPI UCSAPI_GetUserInfoListFromTerminal(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID);

	UCSAPI_RETURN UCSAPI UCSAPI_GetUserDataFromTerminal(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32 TerminalID, 
		IN UCSAPI_UINT32 UserID);

	UCSAPI_RETURN UCSAPI UCSAPI_GetAccessLogCountFromTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_GET_LOG_TYPE LogType);

	UCSAPI_RETURN UCSAPI UCSAPI_GetAccessLogCountFromTerminalEx(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_GET_LOG_TYPE LogType,
		IN UCSAPI_DATE_PERIOD_PTR Period);


	UCSAPI_RETURN UCSAPI UCSAPI_GetAccessLogFromTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_GET_LOG_TYPE LogType);

	UCSAPI_RETURN UCSAPI UCSAPI_GetAccessLogFromTerminalEx(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_GET_LOG_TYPE LogType,
		IN UCSAPI_DATE_PERIOD_PTR Period);

	UCSAPI_RETURN UCSAPI UCSAPI_SendAuthInfoToTerminal(
		IN UCSAPI_UINT32 TerminalID, 
		IN UCSAPI_AUTH_INFO_PTR pUserAuthType);

	UCSAPI_RETURN UCSAPI UCSAPI_SendAntipassbackResultToTerminal(
		IN UCSAPI_UINT32 TerminalID, 
		IN UCSAPI_UINT32 UserID, 
		IN UCSAPI_BOOL bResult);

	UCSAPI_RETURN UCSAPI UCSAPI_SendAuthResultToTerminal(
		IN UCSAPI_UINT32 TerminalID, 
		IN UCSAPI_AUTH_NOTIFY_PTR pResult);

	UCSAPI_RETURN UCSAPI UCSAPI_GetTerminalCount(
		IN UCSAPI_UINT32* pCount);

	UCSAPI_RETURN UCSAPI UCSAPI_GetFirmwareVersionFromTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID);

	UCSAPI_RETURN UCSAPI UCSAPI_UpgradeFirmwareToTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_CHAR_PTR pFilePath);

	UCSAPI_RETURN UCSAPI UCSAPI_GetOptionFromTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID);

	UCSAPI_RETURN UCSAPI UCSAPI_SetOptionToTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID, 
		IN UCSAPI_TERMINAL_OPTION_PTR pOption);

	UCSAPI_RETURN UCSAPI UCSAPI_GetOptionFromACU(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID);

	UCSAPI_RETURN UCSAPI UCSAPI_SetOptionToACU(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID, 
		IN UCSAPI_ACU_OPTION_FLAG fOption,
		IN UCSAPI_ACU_OPTION_PTR pOption);

	UCSAPI_RETURN UCSAPI UCSAPI_GetLockScheduleFromACU(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8 LockIndex);

	UCSAPI_RETURN UCSAPI UCSAPI_SetLockScheduleToACU(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8 LockIndex,
		IN UCSAPI_TERMINAL_SCHEDULE_PTR pSchedule);

	UCSAPI_RETURN UCSAPI UCSAPI_TerminalOptionDialog(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID);
	
	UCSAPI_RETURN UCSAPI UCSAPI_OpenDoorToTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID);

	UCSAPI_RETURN UCSAPI UCSAPI_SetDoorStatusToTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8 Status);

	UCSAPI_RETURN UCSAPI UCSAPI_SetDoorStatusToACU(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8 Status,
		IN UCSAPI_UINT8 DoorID);

	UCSAPI_RETURN UCSAPI UCSAPI_ControlPeripheralDevice(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_PERIPHERAL_DEVICE* PeripheralDevice);

	UCSAPI_RETURN UCSAPI UCSAPI_GetMealConfigFromTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID);

	UCSAPI_RETURN UCSAPI UCSAPI_SetMealConfigToTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_TERMINAL_MEAL_CONFIG_PTR pMealConfig);

	UCSAPI_RETURN UCSAPI UCSAPI_GetTAFunctionFromTerminal(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID);

	UCSAPI_RETURN UCSAPI UCSAPI_SetTAFunctionToTerminal(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID,
		IN UCSAPI_UINT32  TAMode);

	UCSAPI_RETURN UCSAPI UCSAPI_SetTATimeToTerminal(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID,
		IN UCSAPI_TA_TIME*  pTATime);

	/*
	UCSAPI_RETURN UCSAPI UCSAPI_SetTerminalSchedule(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_SINT32  TerminalID);
	*/
	
	UCSAPI_RETURN UCSAPI UCSAPI_EnrollFromTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		OUT UCBioAPI_EXPORT_DATA_PTR pFingerData);

	UCSAPI_RETURN UCSAPI UCSAPI_FreeExportData(
		IN UCBioAPI_EXPORT_DATA_PTR pFingerData);

	UCSAPI_RETURN UCSAPI UCSAPI_SetAccessControlDataToTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_ACCESS_CONTROL_DATA_PTR pAccessControlData);

	UCSAPI_RETURN UCSAPI UCSAPI_SetSkinResource(
		IN UCSAPI_CHAR_PTR  szSkinPath);

	UCSAPI_RETURN UCSAPI UCSAPI_SetFingerImageSend(IN UCSAPI_BOOL IsSend);

	UCSAPI_RETURN UCSAPI UCSAPI_SendPrivateMessageToTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT32 Reserved,
		IN UCSAPI_PRIVATE_MESSAGE_PTR Message);

	UCSAPI_RETURN UCSAPI UCSAPI_SendPublicMessageToTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_BOOL Show,
		IN UCSAPI_PUBLIC_MESSAGE_PTR Message);

	UCSAPI_RETURN UCSAPI UCSAPI_SendUserFileToTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT32 FileType,
		IN UCSAPI_CHAR_PTR FilePath);

	UCSAPI_RETURN UCSAPI UCSAPI_SetSmartCardLayoutToTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_SMARTCARD_LAYOUT_PTR pCardLayout);

	UCSAPI_RETURN UCSAPI UCSAPI_GetTerminalInfo(
		IN UCSAPI_UINT32 TerminalID,
		OUT UCSAPI_TERMINAL_INFO_PTR pInfo);

	UCSAPI_RETURN UCSAPI UCSAPI_SetTerminalTimezone(
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_CHAR_PTR pTimezoneName);

	UCSAPI_RETURN UCSAPI UCSAPI_SetError(
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_ERROR_TYPE ErrorType);
	
	UCSAPI_RETURN UCSAPI UCSAPI_SetWiegandFormatToTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_WIEGAND_DATA_TYPE	wgdType,
		IN UCSAPI_CHAR_PTR FilePath);

	UCSAPI_RETURN UCSAPI UCSAPI_SetEmergencyToTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_SET_EMERGENCY_INFO_PTR Emergency);

	UCSAPI_RETURN UCSAPI UCSAPI_SendTerminalControl(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT32 lockStatus,
		IN UCSAPI_UINT32 lockType);

	UCSAPI_RETURN UCSAPI UCSAPI_RegistFaceFromTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8  opt);

	UCSAPI_RETURN UCSAPI UCSAPI_SendSirenToTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8	 opt,
		IN UCSAPI_UINT8	 cntSiren,
		IN UCSAPI_SIREN_CONFIG_PTR	pSiren);

	UCSAPI_RETURN UCSAPI UCSAPI_GetFpMinutiaeFromTerminal(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8	 minType,
		IN UCSAPI_UINT8	 minCount);

#endif/* _UCSAPI_LOAD_LIBRARY */

	typedef UCSAPI_RETURN (UCSAPI *UCSAPI_ServerStart_PTR) (
		IN UCSAPI_UINT32 MaxTerminal,
		IN UCSAPI_UINT32 Port,
		IN UCSAPI_UINT32  Reserved,
		IN UCSAPI_CALLBACK_EVENT_HANDLER CallbackEventFunction);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_ServerStop_PTR)();

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_AddUserToTerminal_PTR)(
		IN UCSAPI_UINT16		ClientID,
		IN UCSAPI_UINT32		TerminalID,
		IN UCSAPI_BOOL			IsOverwrite,
		IN UCSAPI_USER_DATA_PTR pUserData);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_DeleteUserFromTerminal_PTR)(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID, 
		IN UCSAPI_UINT32  UserID);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_DeleteAllUserFromTerminal_PTR)(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetUserCountFromTerminal_PTR)(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetUserInfoListFromTerminal_PTR)(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetUserDataFromTerminal_PTR)(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32 TerminalID, 
		IN UCSAPI_UINT32 UserID);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetAccessLogFromTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_GET_LOG_TYPE LogType);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetAccessLogFromTerminalEx_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_GET_LOG_TYPE LogType,
		IN UCSAPI_DATE_PERIOD_PTR Period);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetAccessLogCountFromTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_GET_LOG_TYPE LogType);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetAccessLogCountFromTerminalEx_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_GET_LOG_TYPE LogType,
		IN UCSAPI_DATE_PERIOD_PTR Period);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SendAuthInfoToTerminal_PTR)(
		IN UCSAPI_UINT32 TerminalID, 
		IN UCSAPI_AUTH_INFO_PTR pUserAuthInfo);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SendAntipassbackResultToTerminal_PTR)(
		IN UCSAPI_UINT32 TerminalID, 
		IN UCSAPI_UINT32 UserID, 
		IN UCSAPI_BOOL bResult);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SendAuthResultToTerminal_PTR)(
		IN UCSAPI_UINT32 TerminalID, 
		IN UCSAPI_AUTH_NOTIFY_PTR pResult);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetTerminalCount_PTR)(
		IN UCSAPI_UINT32* pCount);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetFirmwareVersionFromTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_UpgradeFirmwareToTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_CHAR_PTR pFilePath);
	
	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetOptionFromTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetOptionToTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID, 
		IN UCSAPI_TERMINAL_OPTION_PTR Options);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetOptionFromACU_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetOptionToACU_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID, 
		IN UCSAPI_ACU_OPTION_FLAG fOption,
		IN UCSAPI_ACU_OPTION_PTR pOption);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetLockScheduleFromACU_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8 LockIndex);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetLockScheduleToACU_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8 LockIndex,
		IN UCSAPI_TERMINAL_SCHEDULE_PTR pSchedule);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_TerminalOptionDialog_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID);
	
	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_OpenDoorToTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID);
	
	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetDoorStatusToTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8 Status);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetDoorStatusToACU_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8 Status,
		IN UCSAPI_UINT8 DoorID);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_ControlPeripheralDevice_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_PERIPHERAL_DEVICE* PeripheralDevice);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetMealConfigFromTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetMealConfigToTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_TERMINAL_MEAL_CONFIG_PTR MealConfig);


	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetTAFunctionFromTerminal_PTR)(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetTAFunctionToTerminal_PTR)(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID,
		IN UCSAPI_UINT32  TAMode);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetTATimeToTerminal_PTR)(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_UINT32  TerminalID,
		IN UCSAPI_TA_TIME*  pTATime);

	/*
	typedef  UCSAPI_RETURN (UCSAPI* UCSAPI_SetTerminalSchedule_PTR)(
		IN UCSAPI_UINT16  ClientID,
		IN UCSAPI_SINT32  TerminalID);
	*/

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_EnrollFromTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		OUT UCBioAPI_EXPORT_DATA_PTR pFingerData);


	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_FreeExportData_PTR)(
		IN UCBioAPI_EXPORT_DATA_PTR pFingerData);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetAccessControlDataToTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_ACCESS_CONTROL_DATA_PTR pAccessControlData);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetSkinResource_PTR)(
		IN UCSAPI_CHAR_PTR szSkinPath);
	
	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetFingerImageSend_PTR)(
		IN UCSAPI_BOOL IsSend);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SendPrivateMessageToTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT32 Reserved,
		IN UCSAPI_PRIVATE_MESSAGE_PTR Message);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SendPublicMessageToTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_BOOL Show,
		IN UCSAPI_PUBLIC_MESSAGE_PTR Message);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SendUserFileToTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT32 FileType,
		IN UCSAPI_CHAR_PTR FilePath);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetSmartCardLayoutToTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_SMARTCARD_LAYOUT_PTR pCardLayout);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetTerminalInfo_PTR)(
		IN UCSAPI_UINT32 TerminalID,
		OUT UCSAPI_TERMINAL_INFO_PTR pInfo);
	
	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetTerminalTimezone_PTR)(
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_CHAR_PTR pTimezoneName);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetError_PTR)(
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_ERROR_TYPE ErrorType);
	
	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetWiegandFormatToTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_WIEGAND_DATA_TYPE	wgdType,
		IN UCSAPI_CHAR_PTR FilePath);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SetEmergencyToTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_SET_EMERGENCY_INFO_PTR Emergency);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SendTerminalControl_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT32 lockStatus,
		IN UCSAPI_UINT32 lockType);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_RegistFaceFromTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8  opt);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_SendSirenToTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8	 opt,
		IN UCSAPI_UINT8	 cntSiren,
		IN UCSAPI_SIREN_CONFIG_PTR	pSiren);

	typedef UCSAPI_RETURN (UCSAPI* UCSAPI_GetFpMinutiaeFromTerminal_PTR)(
		IN UCSAPI_UINT16 ClientID,
		IN UCSAPI_UINT32 TerminalID,
		IN UCSAPI_UINT8	 minType,
		IN UCSAPI_UINT8	 minCount);

#ifdef __cplusplus
}
#endif

#endif  /* _UCSAPI_H_INCLUDED */
