
#ifndef _UCSAPIERR_H_INCLUDED
#define _UCSAPIERR_H_INCLUDED
 
#define	UCSAPIERR_BASE_GENERAL					(0x0000)
#define	UCSAPIERR_BASE_INIT						(0x0100)
#define	UCSAPIERR_BASE_MEMORY					(0x0200)
#define	UCSAPIERR_BASE_AUTHENTICATION			(0x0300)
#define	UCSAPIERR_BASE_TERMINAL					(0x0400)

// Basic error definitions
#define UCSAPIERR_NONE							(0)
#define UCSAPIERR_INVALID_POINTER				(UCSAPIERR_BASE_GENERAL + 0x01)
#define UCSAPIERR_INVALID_TYPE					(UCSAPIERR_BASE_GENERAL + 0x02)
#define UCSAPIERR_INVALID_PARAMETER				(UCSAPIERR_BASE_GENERAL + 0x03)
#define UCSAPIERR_INVALID_DATA					(UCSAPIERR_BASE_GENERAL + 0x04)
#define UCSAPIERR_FUNCTION_FAIL		            (UCSAPIERR_BASE_GENERAL + 0x05)
#define UCSAPIERR_NOT_SERVER_ACTIVE				(UCSAPIERR_BASE_GENERAL + 0x06)
#define UCSAPIERR_INVALID_TERMINAL				(UCSAPIERR_BASE_GENERAL + 0x07)
#define UCSAPIERR_PROCESS_FAIL					(UCSAPIERR_BASE_GENERAL + 0x08)
#define UCSAPIERR_USER_CANCEL					(UCSAPIERR_BASE_GENERAL + 0x09)
#define UCSAPIERR_UNKNOWN_REASON				(UCSAPIERR_BASE_GENERAL + 0x10)

// Data size related error definitions
#define UCSAPIERR_CODE_SIZE						(UCSAPIERR_BASE_MEMORY + 0x01)
#define UCSAPIERR_USER_ID_SIZE					(UCSAPIERR_BASE_MEMORY + 0x02)
#define UCSAPIERR_USER_NAME_SIZE				(UCSAPIERR_BASE_MEMORY + 0x03)
#define UCSAPIERR_UNIQUE_ID_SIZE				(UCSAPIERR_BASE_MEMORY + 0x04)
#define UCSAPIERR_INVALID_SECURITY_LEVEL		(UCSAPIERR_BASE_MEMORY + 0x05)
#define UCSAPIERR_PASSWORD_SIZE					(UCSAPIERR_BASE_MEMORY + 0x06)
#define UCSAPIERR_PICTURE_SIZE					(UCSAPIERR_BASE_MEMORY + 0x07)
#define UCSAPIERR_INVALID_PICTURE_TYPE			(UCSAPIERR_BASE_MEMORY + 0x08)
#define UCSAPIERR_RFID_SIZE						(UCSAPIERR_BASE_MEMORY + 0x09)
#define UCSAPIERR_INVALID_INDEX					(UCSAPIERR_BASE_MEMORY + 0x10)
#define UCSAPIERR_MAX_CARD_NUMBER				(UCSAPIERR_BASE_MEMORY + 0x11)
#define UCSAPIERR_MAX_FINGER_NUMBER				(UCSAPIERR_BASE_MEMORY + 0x12)
#define UCSAPIERR_MAX_TIMEZONE_NUMBER			(UCSAPIERR_BASE_MEMORY + 0x13)
#define UCSAPIERR_MAX_HOLIDAY_NUMBER			(UCSAPIERR_BASE_MEMORY + 0x14)
#define UCSAPIERR_MAX_ACCESS_TIME_NUMBER		(UCSAPIERR_BASE_MEMORY + 0x15)
#define UCSAPIERR_MAX_ACCESS_GROUP_NUMBER		(UCSAPIERR_BASE_MEMORY + 0x16)
#define UCSAPIERR_OVER_MAXIMUM					(UCSAPIERR_BASE_MEMORY + 0x17)

// Authentication related error definitions
// 뒤의 값은 AccessLog의 Result값임.
#define UCSAPIERR_INVALID_USER					(UCSAPIERR_BASE_AUTHENTICATION + 0x01)
#define UCSAPIERR_UNAUTHORIZED					(UCSAPIERR_BASE_AUTHENTICATION + 0x02)
#define UCSAPIERR_PERMISSION					(UCSAPIERR_BASE_AUTHENTICATION + 0x03)
#define UCSAPIERR_FINGER_CAPTURE_FAIL			(UCSAPIERR_BASE_AUTHENTICATION + 0x04)
#define UCSAPIERR_DUP_AUTHENTICAION				(UCSAPIERR_BASE_AUTHENTICATION + 0x05)
#define UCSAPIERR_ANTIPASSBSCK					(UCSAPIERR_BASE_AUTHENTICATION + 0x06)
#define UCSAPIERR_NETWORK						(UCSAPIERR_BASE_AUTHENTICATION + 0x07)
#define UCSAPIERR_SERVER_BUSY					(UCSAPIERR_BASE_AUTHENTICATION + 0x08)
#define UCSAPIERR_FACE_DETECTION				(UCSAPIERR_BASE_AUTHENTICATION + 0x09)
#define UCSAPIERR_BLACKLIST						(UCSAPIERR_BASE_AUTHENTICATION + 0x0a)
#define UCSAPIERR_MEAL_PAY						(UCSAPIERR_BASE_AUTHENTICATION + 0x0b)
#define UCSAPIERR_MEAL_TYPE						(UCSAPIERR_BASE_AUTHENTICATION + 0x0c)
#define UCSAPIERR_MEAL_CODE						(UCSAPIERR_BASE_AUTHENTICATION + 0x0d)
#define UCSAPIERR_PERIOD						(UCSAPIERR_BASE_AUTHENTICATION + 0x0e)
#define UCSAPIERR_MEAL_LIMIT					(UCSAPIERR_BASE_AUTHENTICATION + 0x0f)
#define UCSAPIERR_DAY_LIMIT						(UCSAPIERR_BASE_AUTHENTICATION + 0x10)
#define UCSAPIERR_MONTH_LIMIT					(UCSAPIERR_BASE_AUTHENTICATION + 0x11)
#define UCSAPIERR_SOFT_PASSBACK					(UCSAPIERR_BASE_AUTHENTICATION + 0x20)
#define UCSAPIERR_DURESS_FINGER					(UCSAPIERR_BASE_AUTHENTICATION + 0x21)
#define UCSAPIERR_INVALID_ISSUE					(UCSAPIERR_BASE_AUTHENTICATION + 0x22)
#define UCSAPIERR_INVALID_TIME					(UCSAPIERR_BASE_AUTHENTICATION + 0x23)
#define UCSAPIERR_INVALID_PHONE					(UCSAPIERR_BASE_AUTHENTICATION + 0x24)
#define UCSAPIERR_AUTH_UNDEFINED				(UCSAPIERR_BASE_AUTHENTICATION + 0xff)

#define UCSAPIERR_USER_REGISTRATION				(UCSAPIERR_BASE_TERMINAL + 0x01)	// 5001
#define UCSAPIERR_FW_RESOURCE					(UCSAPIERR_BASE_TERMINAL + 0x02)	// 5002
#define UCSAPIERR_FW_UPGRADE					(UCSAPIERR_BASE_TERMINAL + 0x03)
#define UCSAPIERR_FW_VERSION					(UCSAPIERR_BASE_TERMINAL + 0x04)	// 5007
#define UCSAPIERR_FRESH_MEMORY					(UCSAPIERR_BASE_TERMINAL + 0x05)
#define UCSAPIERR_NOT_FOUND_USER				(UCSAPIERR_BASE_TERMINAL + 0x06)
#define UCSAPIERR_SIMILAR_FP					(UCSAPIERR_BASE_TERMINAL + 0x07)	// 7006 
#define UCSAPIERR_DUPLICATE_USER				(UCSAPIERR_BASE_TERMINAL + 0x08)
#define UCSAPIERR_DUPLICATE_RFID				(UCSAPIERR_BASE_TERMINAL + 0x09)

// Terminal related error definitions
#define UCSAPIERR_INVALID_CHECKSUM				(UCSAPIERR_BASE_TERMINAL + 0x01)

#endif /* _UCSAPIERR_H_INCLUDED */